### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by 863689877** [weiyithu/PV-RAFT#2]
Hi, it is a great job!
Could you provide the visualization code that produces the following effect in your paper, Thank you!
![图片](https://user-images.githubusercontent.com/48486151/120950344-2a533b00-c779-11eb-8c54-7f329ca52195.png)

**Comment by weiyithu** [comment]
Hi,
  I have add visualization code (visual.py). We use mayavi for visualization and you should intall it before running visual.py.

**Comment by 863689877** [comment]
Thank you
